### ISSUE TITLE
Reflections class not able to find dev.valentinspac.proxy package

### ISSUE THREAD

**Issue by FuncGuy** [spac-valentin/jdk-dynamic-proxy#1]
Not able to find the annotation TransactionalService.class throwing error.

**Comment by spac-valentin** [comment]
@FuncGuy that's strange, it works for me. Can you share the error you see (stacktrace)?

**Comment by FuncGuy** [comment]
Exception in thread "main" java.lang.RuntimeException: No Bean found for class interface dev.valentinspac.proxy.service.Playable
	at dev.valentinspac.proxy.framework.ProxyFactory.lambda$getBean$1(ProxyFactory.java:83)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at dev.valentinspac.proxy.framework.ProxyFactory.getBean(ProxyFactory.java:83)
	at dev.valentinspac.proxy.ProxyApp.main(ProxyApp.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

**Comment by FuncGuy** [comment]
works only if i change to following and my current os  is ubuntu
Reflections reflections = new Reflections(PlayerService.class);

**Comment by spac-valentin** [comment]
@FuncGuy are you sure it works as expected? `PlayerService` is in `dev.valentinspac.proxy.service` so you would instantiate `Reflections` only within that package, making `reflections.getTypesAnnotatedWith(TransactionalService.class)`  return nothing

**Comment by spac-valentin** [comment]
@FuncGuy indeed seems to not work for Ubuntu. This is the fix: https://github.com/spac-valentin/jdk-dynamic-proxy/commit/45c177353487df3276a5b2aad2072ba9f6d24c67 Thanks for pointing this out 👍
